spring.application.name=tablero-medidores
spring.profiles.active=dev

logging.level.org.springframework.security=TRACE

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=agburgos83@gmail.com
spring.mail.password=tvux javx irrc ffcy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.debug=true


