spring.application.name=tablero-medidores
spring.profiles.active=dev

# google login
# spring.security.oauth2.client.registration.google.client-id=745558704114-bhfdfhmqvgdkr0uf4b6ovdjc5ovclq4h.apps.googleusercontent.com
# spring.security.oauth2.client.registration.google.client-secret=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

logging.level.org.springframework.security=TRACE

